### ISSUE TITLE
Recording enhancements 

### ISSUE THREAD

**Issue by devnulling** [maia-sdr/maia-sdr#3]
It would be really nice if it was possible to define a set number of samples that would be captured. (such as 100e6 samples, which at 40e6 sample rate results in a 2.5 second file) Another way could be to just define the time of a capture.

It would also be super nice if the filename could default to the timestamp with a keyword that is set, the sigmf-recorder utility that is on Gitlab will output something like this:

2022-07-23-23-20-25_keyword_F440000000_G30.sigmf

**Comment by daniestevez** [comment]
Thanks for the suggestions.

Currently, while the recording is being made, the "Record" button turns into a "Stop" button. When pressed, the recording finishes immediately. This feature may not be so evident a high sample rates, because the 400MiB are exhausted quickly. This gives a way to do recordings of an approximate duration.

I really want the web UI to be usable in the field on a phone screen, so I'm a bit careful about bloating it with many fields and options. But a field to set the maximum recording length (in units of seconds makes the most sense to me) would fit well in the recording properties/metadata dialog, like so:

![duration-dialog](https://user-images.githubusercontent.com/15093841/218566673-fe3f20b2-2cbd-4b1e-90e4-ffc44a021e89.png)

This field being empty (or perhaps having a value of zero, in case we want to make the field an `<input type="number">`) would indicate the current behaviour. If there is a positive number in the field, the recording will last for that number of seconds or 400MiB, whichever happens first.

As to how to implement this, my current idea is a bit convoluted, but doesn't need major changes. The DMA that writes the IQ data to the DDR doesn't count samples currently. In fact it works with 64-bit words, so counting samples in 12-bit mode is tricky. However, a good idea is that it's not necessary to make the DMA write exactly the amount of IQ samples we want. It can write more (without exceeding the 400MiB buffer). When the user downloads the SigMF recording, we can produce a file of the exact required length.

What we want is for the DMA to stop shortly after the required amount of samples have been written (to avoid having the user to wait for too long for the recording to finish). Currently the server software can know how many bytes the DMA has written by reading a register. So what we could do on the software is to spawn a concurrent task that sleeps for the required recording duration, and then polls this register to make sure that enough bytes have been written (just in case the sleep was slightly shorter than needed). Then it can send the stop command to the DMA (which would work in the same way as if the user had pressed the stop button on the web UI). We can be clever and not spawn the task if the maximum duration is longer than what fits in 400MiB.

---

Regarding filenames, I like that idea, because it's a bother to have to keep changing the filename manually to avoid having files with the same filename (what's worse, if you download a file called `recording.sigmf` twice, the web browser will typically rename the second to `recording (1).sigmf`, and this technically breaks the SigMF archive, because the folder and files inside are still called `recording`). I thought about having an increasing counter (`recording01`, etc.), but having the timestamp is much better.

The question is how to make this compatible with the current method of choosing a filename manually.

An idea is that if the filename is blank (and it can be blank by default, and cleared when the recording download is initiated), then the filename is built as `2022-07-23-23-20-25_maiasdr_F440000000_G30.sigmf` (I've just stolen the idea to include `maiasdr` as the keyword from `gqrx`, which always names its recordings as `gqrx...`).

It would be good if the user could enter their own keyword, but I don't know how to easily make that compatible with choosing the filename completely manually (if there is some text in the Filename field, is it the keyword or the full filename?).

If we go fancy we could let the Filename be a template a-là `strftime()`, and have it default to something like `%T_keyword_F%F_G%g` (which with some fantasy means exactly what you proposed).

**Comment by jacobagilbert** [comment]
I think you maximum duration proposal is great, and would be very useful.

Maybe for the filename you could have a simple checkbox for datetime prepending? I understand the concern about bloating the UI though....
<img width="452" alt="image" src="https://user-images.githubusercontent.com/7121282/219711471-4177b26b-57cb-4deb-bf77-cf5c5880c1d9.png">

**Comment by karatemir** [comment]
@daniestevez  great work!
> Currently the server software can know how many bytes the DMA has written by reading a register. 

Can you please point to the exact line where this is done?

**Comment by daniestevez** [comment]
> @daniestevez great work!
> 
> > Currently the server software can know how many bytes the DMA has written by reading a register.
> 
> Can you please point to the exact line where this is done?

Here is the function call in the code that gets run to generate the SigMF file:

https://github.com/maia-sdr/maia-sdr/blob/9458fa4e5e08e76d233a25ca5d7cab18d5040420/maia-httpd/src/httpd/recording.rs#L219

And here is the implementation of that function:

https://github.com/maia-sdr/maia-sdr/blob/9458fa4e5e08e76d233a25ca5d7cab18d5040420/maia-httpd/src/fpga.rs#L286

**Comment by karatemir** [comment]
@daniestevez kind of a tangential question, but is it possible to use the currently available infrastructure to replay a sigmf recording (using the waterfall component etc.)?

**Comment by daniestevez** [comment]
Currently it isn't possible. A DMA to send the recording back to the FPGA to compute its waterfall is missing.
